### ISSUE TITLE
CP calendar is not working.

### ISSUE THREAD

**Issue by getlost01** [vasuksh/CP-calendar-extension#1]
### Error : 

`Access to XMLHttpRequest at https://shrouded-shore-92504.herokuapp.com/https://clist.by/api/v2/contest/?username=vasuKsh&api_key=ba837437c15539752557a401791572a0493f7ee9&limit=150&end__gt=2022-12-16T00:00:00&order_by=start from origin 'chrome-extension://gnnibhojjocbjpkhhlphelmiiffodajj' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Since Heroku has to stop free services so  `https://shrouded-shore-92504.herokuapp.com/` not working.

### Solution :

Do use another Cors blocking site. Refer [here for alternatives](https://nordicapis.com/10-free-to-use-cors-proxies/)

<img width="500" alt="Screenshot 2022-12-16 at 7 27 41 PM" src="https://user-images.githubusercontent.com/79409258/208114901-8a8aec2b-78fc-4a3c-a1ce-7e6b64975fb9.png">

**Comment by vasuksh** [comment]
Hey @getlost01 , I have resolved the issue by creating a custom proxy since other proxies were not working for me.
I have published the changes in chrome webstore and it will be will be updated once it  is reviewed by there teams.
